[package]
name = "rust-mustache"
version = "0.3.0"
authors = ["erick.tryzelaar@gmail.com"]
license = "MIT/Apache-2.0"
description = "A pure rust implementation of mustache"
repository = "https://github.com/erickt/rust-mustache"

[lib]
name = "mustache"
